### ISSUE TITLE
iOS Build Failure after updating to 9.2.1: "using sysroot for 'MacOSX' but targeting 'iPhone'"

### ISSUE THREAD

**Issue by corepuncher** [dart-lang/native#2835]
After upgrading objective_c from 9.1.0 to 9.2.1, my iOS build fails immediately with sysroot mismatch errors.

It appears the build hook is incorrectly pointing to the MacOSX SDK while trying to compile for iOS, resulting in availability errors for SecAsn1Item (which exists in macOS Security framework but is unavailable in iOS).

```
INFO: clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]

/Applications/Xcode.app/.../System/Library/Frameworks/Security.framework/Headers/cssmtype.h:95:9: error: 'SecAsn1Item' is unavailable: not available on iOS
/Applications/Xcode.app/.../System/Library/Frameworks/Security.framework/Headers/cssmtype.h:1282:5: error: 'SecAsn1Oid' is unavailable: not available on iOS
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Workaround**: Pinning objective_c: 9.1.0 in pubspec.yaml resolves the issue immediately and the app builds successfully.

Flutter 3.38.3
Xcode 16.0
macOS Sequoia 15.6.1

**Comment by dcharkes** [comment]
@liamappelbe This is likely an issue with `package:native_toolchain_c`, could you please investigate. (I am OOO.)

cc @goderbauer

**Comment by liamappelbe** [comment]
Hmmm, that's weird. The errors are coming from the Security framework, but package:objective_c doesn't use that framework. I've also successfully built iOS apps using package:objective_c, so there must be something specific about this setup.

@corepuncher Can you share a minimal repro case, or point me to the repo where the failure is happening so I can try to repro it?

**Comment by corepuncher** [comment]
> Hmmm, that's weird. The errors are coming from the Security framework, but package:objective_c doesn't use that framework. I've also successfully built iOS apps using package:objective_c, so there must be something specific about this setup.
> 
> [@corepuncher](https://github.com/corepuncher) Can you share a minimal repro case, or point me to the repo where the failure is happening so I can try to repro it?

I will eventually get to this, with the holidays and other things, it might be a while so sorry for the probable delay.

**Comment by brianquinlan** [comment]
This seems to be [affecting `package:cupertino_http`](https://github.com/dart-lang/http/issues/1861).
